/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdamoInspiredPortfolioRouteImport } from './routes/adamo-inspired-portfolio'
import { Route as BeltsRouteImport } from './routes/belts'
import { Route as CasualShoesRouteImport } from './routes/casual-shoes'
import { Route as ClassicShoesRouteImport } from './routes/classic-shoes'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ShoesRouteImport } from './routes/shoes'
import { Route as AdamoInspiredPortfolioSplatRouteImport } from './routes/adamo-inspired-portfolio.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdamoInspiredPortfolioRoute = AdamoInspiredPortfolioRouteImport.update({
  id: '/adamo-inspired-portfolio',
  path: '/adamo-inspired-portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const BeltsRoute = BeltsRouteImport.update({
  id: '/belts',
  path: '/belts',
  getParentRoute: () => rootRouteImport,
} as any)
const CasualShoesRoute = CasualShoesRouteImport.update({
  id: '/casual-shoes',
  path: '/casual-shoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassicShoesRoute = ClassicShoesRouteImport.update({
  id: '/classic-shoes',
  path: '/classic-shoes',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ShoesRoute = ShoesRouteImport.update({
  id: '/shoes',
  path: '/shoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdamoInspiredPortfolioSplatRoute =
  AdamoInspiredPortfolioSplatRouteImport.update({
    id: '/$',
    path: '/$',
    getParentRoute: () => AdamoInspiredPortfolioRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/adamo-inspired-portfolio': typeof AdamoInspiredPortfolioRouteWithChildren
  '/belts': typeof BeltsRoute
  '/casual-shoes': typeof CasualShoesRoute
  '/classic-shoes': typeof ClassicShoesRoute
  '/collections': typeof CollectionsRoute
  '/contact': typeof ContactRoute
  '/shoes': typeof ShoesRoute
  '/adamo-inspired-portfolio/$': typeof AdamoInspiredPortfolioSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/adamo-inspired-portfolio': typeof AdamoInspiredPortfolioRouteWithChildren
  '/belts': typeof BeltsRoute
  '/casual-shoes': typeof CasualShoesRoute
  '/classic-shoes': typeof ClassicShoesRoute
  '/collections': typeof CollectionsRoute
  '/contact': typeof ContactRoute
  '/shoes': typeof ShoesRoute
  '/adamo-inspired-portfolio/$': typeof AdamoInspiredPortfolioSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/adamo-inspired-portfolio': typeof AdamoInspiredPortfolioRouteWithChildren
  '/belts': typeof BeltsRoute
  '/casual-shoes': typeof CasualShoesRoute
  '/classic-shoes': typeof ClassicShoesRoute
  '/collections': typeof CollectionsRoute
  '/contact': typeof ContactRoute
  '/shoes': typeof ShoesRoute
  '/adamo-inspired-portfolio/$': typeof AdamoInspiredPortfolioSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/adamo-inspired-portfolio'
    | '/belts'
    | '/casual-shoes'
    | '/classic-shoes'
    | '/collections'
    | '/contact'
    | '/shoes'
    | '/adamo-inspired-portfolio/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/adamo-inspired-portfolio'
    | '/belts'
    | '/casual-shoes'
    | '/classic-shoes'
    | '/collections'
    | '/contact'
    | '/shoes'
    | '/adamo-inspired-portfolio/$'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/adamo-inspired-portfolio'
    | '/belts'
    | '/casual-shoes'
    | '/classic-shoes'
    | '/collections'
    | '/contact'
    | '/shoes'
    | '/adamo-inspired-portfolio/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdamoInspiredPortfolioRoute: typeof AdamoInspiredPortfolioRouteWithChildren
  BeltsRoute: typeof BeltsRoute
  CasualShoesRoute: typeof CasualShoesRoute
  ClassicShoesRoute: typeof ClassicShoesRoute
  CollectionsRoute: typeof CollectionsRoute
  ContactRoute: typeof ContactRoute
  ShoesRoute: typeof ShoesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adamo-inspired-portfolio': {
      id: '/adamo-inspired-portfolio'
      path: '/adamo-inspired-portfolio'
      fullPath: '/adamo-inspired-portfolio'
      preLoaderRoute: typeof AdamoInspiredPortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/belts': {
      id: '/belts'
      path: '/belts'
      fullPath: '/belts'
      preLoaderRoute: typeof BeltsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casual-shoes': {
      id: '/casual-shoes'
      path: '/casual-shoes'
      fullPath: '/casual-shoes'
      preLoaderRoute: typeof CasualShoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classic-shoes': {
      id: '/classic-shoes'
      path: '/classic-shoes'
      fullPath: '/classic-shoes'
      preLoaderRoute: typeof ClassicShoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shoes': {
      id: '/shoes'
      path: '/shoes'
      fullPath: '/shoes'
      preLoaderRoute: typeof ShoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adamo-inspired-portfolio/$': {
      id: '/adamo-inspired-portfolio/$'
      path: '/$'
      fullPath: '/adamo-inspired-portfolio/$'
      preLoaderRoute: typeof AdamoInspiredPortfolioSplatRouteImport
      parentRoute: typeof AdamoInspiredPortfolioRoute
    }
  }
}

interface AdamoInspiredPortfolioRouteChildren {
  AdamoInspiredPortfolioSplatRoute: typeof AdamoInspiredPortfolioSplatRoute
}

const AdamoInspiredPortfolioRouteChildren: AdamoInspiredPortfolioRouteChildren =
  {
    AdamoInspiredPortfolioSplatRoute: AdamoInspiredPortfolioSplatRoute,
  }

const AdamoInspiredPortfolioRouteWithChildren =
  AdamoInspiredPortfolioRoute._addFileChildren(
    AdamoInspiredPortfolioRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdamoInspiredPortfolioRoute: AdamoInspiredPortfolioRouteWithChildren,
  BeltsRoute: BeltsRoute,
  CasualShoesRoute: CasualShoesRoute,
  ClassicShoesRoute: ClassicShoesRoute,
  CollectionsRoute: CollectionsRoute,
  ContactRoute: ContactRoute,
  ShoesRoute: ShoesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
