/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CoatsRouteImport } from './routes/coats'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ShirtsRouteImport } from './routes/shirts'
import { Route as ShoesRouteImport } from './routes/shoes'
import { Route as SuitsRouteImport } from './routes/suits'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CoatsRoute = CoatsRouteImport.update({
  id: '/coats',
  path: '/coats',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ShirtsRoute = ShirtsRouteImport.update({
  id: '/shirts',
  path: '/shirts',
  getParentRoute: () => rootRouteImport,
} as any)
const ShoesRoute = ShoesRouteImport.update({
  id: '/shoes',
  path: '/shoes',
  getParentRoute: () => rootRouteImport,
} as any)
const SuitsRoute = SuitsRouteImport.update({
  id: '/suits',
  path: '/suits',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/coats': typeof CoatsRoute
  '/collections': typeof CollectionsRoute
  '/contact': typeof ContactRoute
  '/shirts': typeof ShirtsRoute
  '/shoes': typeof ShoesRoute
  '/suits': typeof SuitsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/coats': typeof CoatsRoute
  '/collections': typeof CollectionsRoute
  '/contact': typeof ContactRoute
  '/shirts': typeof ShirtsRoute
  '/shoes': typeof ShoesRoute
  '/suits': typeof SuitsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/coats': typeof CoatsRoute
  '/collections': typeof CollectionsRoute
  '/contact': typeof ContactRoute
  '/shirts': typeof ShirtsRoute
  '/shoes': typeof ShoesRoute
  '/suits': typeof SuitsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/coats'
    | '/collections'
    | '/contact'
    | '/shirts'
    | '/shoes'
    | '/suits'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/coats'
    | '/collections'
    | '/contact'
    | '/shirts'
    | '/shoes'
    | '/suits'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/coats'
    | '/collections'
    | '/contact'
    | '/shirts'
    | '/shoes'
    | '/suits'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CoatsRoute: typeof CoatsRoute
  CollectionsRoute: typeof CollectionsRoute
  ContactRoute: typeof ContactRoute
  ShirtsRoute: typeof ShirtsRoute
  ShoesRoute: typeof ShoesRoute
  SuitsRoute: typeof SuitsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coats': {
      id: '/coats'
      path: '/coats'
      fullPath: '/coats'
      preLoaderRoute: typeof CoatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shirts': {
      id: '/shirts'
      path: '/shirts'
      fullPath: '/shirts'
      preLoaderRoute: typeof ShirtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shoes': {
      id: '/shoes'
      path: '/shoes'
      fullPath: '/shoes'
      preLoaderRoute: typeof ShoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suits': {
      id: '/suits'
      path: '/suits'
      fullPath: '/suits'
      preLoaderRoute: typeof SuitsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CoatsRoute: CoatsRoute,
  CollectionsRoute: CollectionsRoute,
  ContactRoute: ContactRoute,
  ShirtsRoute: ShirtsRoute,
  ShoesRoute: ShoesRoute,
  SuitsRoute: SuitsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
